---
# tasks file for roles/snow
- name: Update ServiceNow CI
  delegate_to: localhost
  snow_record:
    username: "{{ snow_username }}"
    password: "{{ snow_password }}"
    instance: "{{ snow_instance }}"
    state: present
    number: '{{ ansible_hostname }}'
    table: cmdb_ci_server
    lookup_field: name
    data:
      disk_space : '{{ (ansible_mounts| map(attribute="size_total")|map("int")|sum(start=0)|filesizeformat).split(" ")[0] }}'
      cpu_count: '{{ ansible_processor_vcpus }}'
      cpu_core_thread: '{{ ansible_processor_threads_per_core }}'
      #cpu_speed:
      cpu_core_count: '{{ ansible_processor_cores }}'
      dns_domain: '{{ ansible_domain }}'
      os_version: '{{ ansible_distribution_major_version }}'
      os: '{{ ansible_distribution_file_variety }}'
      os_service_pack: '{{ ansible_distribution_version }}'
      ip_address: '{{ ansible_default_ipv4.address }}'
      mac_address: '{{ ansible_default_ipv4.macaddress }}'
      host_name: '{{ ansible_hostname }}'
      fqdn: '{{ ansible_fqdn }}'
      ram: "{{ (ansible_memtotal_mb/1000) | round(0,'ceil') }}"
